const COUPONS_MESSAGE_TYPE: "DEALS_COUPONS" = "DEALS_COUPONS";
const PAGE_NUMBER_COUPON_ANALYZER_RANGE: number = 3; // build urls from page 1-3

export { COUPONS_MESSAGE_TYPE, PAGE_NUMBER_COUPON_ANALYZER_RANGE };
